# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - uses: actions/checkout@master
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "joelbirchler/action-test.git"
          source_branch: "master"
          destination_branch: "foo"
          github_token: ${{ secrets.GITHUB_TOKEN }}
